src/main/java/edu/iit/sat/itmd4515/sdeshmu7/fp/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.sdeshmu7.fp.web;

import edu.iit.sat.itmd4515.sdeshmu7.fp.ViewController.AbstractJSFController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

/**
 *
 * @author Sandeep
 */
@Named
@RequestScoped
public class LoginController extends AbstractJSFController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotNull(message = "You must enter a User Name")
    private String username;
    @NotNull(message = "You must enter a password")
    private String password;

    public LoginController() {
    }

    @Override
    @PostConstruct
    protected void postConstruct() {

        super.postConstruct();
    }

    public String getRemoteUser() {
        return facesContext.getExternalContext().getRemoteUser();
    }

    public boolean isAdmin() {
        return facesContext.getExternalContext().isUserInRole("SystemAdmins");
    }

    public boolean isAgent() {
        return facesContext.getExternalContext().isUserInRole("SystemAgents");
    }

    public boolean isPropertyOwner() {
        return facesContext.getExternalContext().isUserInRole("SystemPropertyOwners");
    }

    public boolean isBuyer() {
        return facesContext.getExternalContext().isUserInRole("SystemBuyers");
    }

    public String getRoleContextPath(String path) {
        if (isAdmin()) {
            return "/admin/" + path + FACES_REDIRECT;
        } else if (isAgent()) {
            return "/agentPortal/" + path + FACES_REDIRECT;
        } else if (isPropertyOwner()) {
            return "/propertyOwnerPortal/" + path + FACES_REDIRECT;
        } else if (isBuyer()) {
            return "/buyerPortal/" + path + FACES_REDIRECT;
        }

        return path;
    }

    public String dologin() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();

        try {
            req.login(username, password);
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username, ex);
            facesContext.addMessage(null, new FacesMessage("Bad Login", "You have entered a bad username or password.Contact the Administrator for SignUp!"));
            return "login.xhtml";
        }

        return getRoleContextPath("Welcome.xhtml");
    }

    public String doLogout() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();

        try {
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username, ex);
            facesContext.addMessage(null, new FacesMessage("Bad Logout"));
            return "login.xhtml";
        }
        return "/login.xhtml";
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/webapp/admin/Welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns ="http://www.w3.org/1999/xhtml">

    <ui:define name="title">
        Administrator Section
    </ui:define>

    <ui:define name="content">
        You are an Admin

        <ul> 
            <li><a href="displayAllAgents.xhtml">All Agents</a></li>
            <li><a href="displayAllBuyers.xhtml">All Buyers</a></li>
            <li><a href="displayAllPropertyOwners.xhtml">All Property Owners</a></li>
            <li><a href="displayAllProperty.xhtml">All Property in the Listing</a></li>
            <br/>
            <br/>
            <br/>
            <li>           <h:form><h:commandLink action="#{adminController.doCreateAgent()}" value ="Create a new Agent for REMS" /> </h:form>
            </li>
            <li>           <h:form><h:commandLink action="#{adminController.doCreateBuyer()}" value ="Create a new Buyer for REMS" /> </h:form>
            </li> 
            <li>           <h:form><h:commandLink action="#{adminController.doCreatePropertyOwner()}" value ="Create a new Property Owner for REMS" /> </h:form>
            </li> 
        </ul>
    </ui:define>

</ui:composition>

src/main/webapp/admin/createNewAgent.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Create a New Agent
    </ui:define>

    <ui:define name="content">
        Agent Details :

        <ezcomp:createNewAgent AgentForRems="#{adminController.newAgentForRems}" UserForRems="#{adminController.userForRems}" action ="#{adminController.executeCreateNewAgent()}" readonly="false" />
    </ui:define>

</ui:composition>

src/main/webapp/admin/createNewBuyer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Create New Buyer
    </ui:define>

    <ui:define name="content">
        <ezcomp:createNewBuyer BuyerForRems="#{adminController.newBuyerForRems}" UserForRems="#{adminController.userForRems}" action ="#{adminController.executeCreateNewBuyer()}" readonly="false" />
    </ui:define>

</ui:composition>

src/main/webapp/admin/createNewPropertyOwner.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Create New Property Owner
    </ui:define>

    <ui:define name="content">
        <ezcomp:createNewPropertyOwner PropertyOwnerForRems="#{adminController.newPropertyOwnerForRems}" UserForRems="#{adminController.userForRems}" action ="#{adminController.executeCreateNewAgent()}" readonly="false" />
    </ui:define>

</ui:composition>

src/main/webapp/admin/displayAllAgents.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        All Agents List
    </ui:define>

    <ui:define name="content">
        <h:dataTable class ="table table-hover table-stripped" value="#{agentService.findAll()}" var="allAgents">
            <h:column>
                <f:facet name="header"><h:outputText value="ID" /></f:facet>
                <h:outputText value="#{allAgents.id}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="Name" /></f:facet>
                <h:outputText value="#{allAgents.name}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="Mobile Number" /></f:facet>
                <h:outputText value="#{allAgents.mobileNumber}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="User Name" /></f:facet>
                <h:outputText value="#{allAgents.userAsAgent.userName}"></h:outputText>
            </h:column>


        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/admin/displayAllBuyers.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        All Buyers List
    </ui:define>

    <ui:define name="content">
        <h:dataTable class ="table table-hover table-stripped" value="#{buyerService.findAll()}" var="allBuyers">
            <h:column>
                <f:facet name="header"><h:outputText value="ID" /></f:facet>
                <h:outputText value="#{allBuyers.id}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="Name" /></f:facet>
                <h:outputText value="#{allBuyers.name}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="city" /></f:facet>
                <h:outputText value="#{allBuyers.city}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="username" /></f:facet>
                <h:outputText value="#{allBuyers.user.userName}"></h:outputText>
            </h:column>


        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/admin/displayAllProperty.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        All the Property are Listed here
    </ui:define>

    <ui:define name="content">
        <h:dataTable class ="table table-hover table-stripped" value="#{propertyService.findAll()}" var="allProperty">
            <h:column>
                <f:facet name="header"><h:outputText value="ID" /></f:facet>
                <h:outputText value="#{allProperty.id}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="Address" /></f:facet>
                <h:outputText value="#{allProperty.address}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="parking" /></f:facet>
                <h:outputText value="#{allProperty.parking.parkingAvailable}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="PropertyOwner name" /></f:facet>
                <h:outputText value="#{allProperty.propertyOwner.name}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header"><h:outputText value="price" /></f:facet>
                <h:outputText value="#{allProperty.price}"></h:outputText>
            </h:column>

            <h:column>
                <h:form> <h:commandLink action="#{adminController.doUpdateProperty(allProperty)}" value="Edit" /></h:form>
            </h:column>
            <h:column>
                <h:form> <h:commandLink action="#{adminController.doDeleteProperty(allProperty)}" value="Delete" /></h:form>
            </h:column>


        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/admin/displayAllPropertyOwners.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:define name="title">
        All Property Owners are listed here
    </ui:define>

    <ui:define name="content">
        <h:dataTable class ="table table-hover table-stripped" value="#{propertyOwnerService.findAll()}" var="allPropertyOwners">
            <h:column>
                <f:facet name="header"><h:outputText value="ID" /></f:facet>
                <h:outputText value="#{allPropertyOwners.id}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="Name" /></f:facet>
                <h:outputText value="#{allPropertyOwners.name}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="MobileNumber" /></f:facet>
                <h:outputText value="#{allPropertyOwners.mobileNumber}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header"><h:outputText value="DateAvailableFrom" /></f:facet>
                <h:outputText value="#{allPropertyOwners.ownsPropertyFromDate}">
                    <f:convertDateTime type="date" />   
                </h:outputText>
            </h:column>

            <h:column>
                <f:facet name="Header"><h:outputText value="UserName" /></f:facet>
                <h:outputText value="#{allPropertyOwners.user.userName}"></h:outputText>
            </h:column>


        </h:dataTable>
    </ui:define>

</ui:composition>

src/main/webapp/admin/editProperty.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="./../WEB-INF/templates/secureTemplate.xhtml"
                xmlns:ezcomp="http://xmlns.jcp.org/jsf/composite/ezcomp">

    <ui:define name="title">
        Edit Property
    </ui:define>

    <ui:define name="content">
        <ezcomp:PropertyInsert PropertyInsert="#{adminController.propertyForUpdate}" action ="#{adminController.executeUpdateProperty()}" readonly="false" />
    </ui:define>

</ui:composition>