src/main/java/edu/iit/sat/itmd4515/sdeshmu7/fp/web/LoginController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.iit.sat.itmd4515.sdeshmu7.fp.web;

import edu.iit.sat.itmd4515.sdeshmu7.fp.ViewController.AbstractJSFController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.NotNull;

/**
 *
 * @author Sandeep
 */
@Named
@RequestScoped
public class LoginController extends AbstractJSFController {

    private static final Logger LOG = Logger.getLogger(LoginController.class.getName());

    @NotNull(message = "You must enter a User Name")
    private String username;
    @NotNull(message = "You must enter a password")
    private String password;

    public LoginController() {
    }

    @Override
    @PostConstruct
    protected void postConstruct() {

        super.postConstruct();
    }

    public String getRemoteUser() {
        return facesContext.getExternalContext().getRemoteUser();
    }

    public boolean isAdmin() {
        return facesContext.getExternalContext().isUserInRole("SystemAdmins");
    }

    public boolean isAgent() {
        return facesContext.getExternalContext().isUserInRole("SystemAgents");
    }

    public boolean isPropertyOwner() {
        return facesContext.getExternalContext().isUserInRole("SystemPropertyOwners");
    }

    public boolean isBuyer() {
        return facesContext.getExternalContext().isUserInRole("SystemBuyers");
    }

    public String getRoleContextPath(String path) {
        if (isAdmin()) {
            return "/admin/" + path + FACES_REDIRECT;
        } else if (isAgent()) {
            return "/agentPortal/" + path + FACES_REDIRECT;
        } else if (isPropertyOwner()) {
            return "/propertyOwnerPortal/" + path + FACES_REDIRECT;
        } else if (isBuyer()) {
            return "/buyerPortal/" + path + FACES_REDIRECT;
        }

        return path;
    }

    public String dologin() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();

        try {
            req.login(username, password);
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username, ex);
            facesContext.addMessage(null, new FacesMessage("Bad Login", "You have entered a bad username or password.Contact the Administrator for SignUp!"));
            return "login.xhtml";
        }

        return getRoleContextPath("Welcome.xhtml");
    }

    public String doLogout() {
        HttpServletRequest req = (HttpServletRequest) facesContext.getExternalContext().getRequest();

        try {
            req.logout();
        } catch (ServletException ex) {
            LOG.log(Level.SEVERE, "Failed login from " + username, ex);
            facesContext.addMessage(null, new FacesMessage("Bad Logout"));
            return "login.xhtml";
        }
        return "/login.xhtml";
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Get the value of password
     *
     * @return the value of password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Set the value of password
     *
     * @param password new value of password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}

src/main/webapp/WEB-INF/templates/publicTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

        <title><ui:insert name="title">Default title</ui:insert></title>

        <!-- Bootstrap -->
        <h:outputStylesheet library="webjars/bootstrap/4.0.0-alpha/css" name="bootstrap.min.css"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </h:head>
    <h:body>

        <h:panelGroup layout="block" class="container">

            <h:panelGroup layout="block" 
                          class="alert alert-warning alert-dismissible"
                          rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h:messages showDetail="false" globalOnly="true" showSummary="true"/>
            </h:panelGroup>

            <h1><ui:insert name="title">Default title</ui:insert></h1>

            <h:messages showDetail="true" errorStyle="color: red" warnStyle="color: orange"
                        infoStyle="color: blue" globalOnly="true" showSummary="true"/>

            <ui:insert name="content">Default content</ui:insert>
        </h:panelGroup>


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <h:outputScript library="webjars/bootstrap/4.0.0-alpha/js" name="bootstrap.min.js"/>
    </h:body>
</html>


src/main/webapp/WEB-INF/templates/secureTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title><ui:insert name="title">Real Estate Management System</ui:insert></title>

        <!-- Bootstrap -->
        <h:outputStylesheet library="webjars/bootstrap/4.0.0-alpha/css" name="bootstrap.min.css"/>
        <h:outputStylesheet library="css" name="starter-template.css"/>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

    </h:head>
    <h:body>

        <nav class="navbar navbar-inverse navbar-dark bg-inverse navbar-fixed-top">
            <a class="navbar-brand" href="#">REMS</a>
            <ul class="nav nav-pills">
                <li class="nav-item active">
                    <h:link outcome="Welcome" value="Home" class="nav-link"/>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/sdeshmu7-fp/About.xhtml">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/sdeshmu7-fp/About.xhtml">Contact</a>
                </li>
                <li class="nav-item">
                    <h:form><h:commandLink class="nav-link"  action="#{loginController.doLogout()}" value="Logout (#{loginController.remoteUser})"/></h:form>
                </li>
            </ul>
        </nav>

        <h:panelGroup layout="block" class="container">

            <h:panelGroup layout="block" 
                          class="alert alert-warning alert-dismissible"
                          rendered="#{not facesContext.validationFailed and not empty facesContext.messageList}">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h:messages showDetail="false" globalOnly="true" showSummary="true"/>
            </h:panelGroup>

            <h1><ui:insert name="title">Default title</ui:insert></h1>

            <h:messages showDetail="true" errorStyle="color: red" warnStyle="color: orange"
                        infoStyle="color: blue" globalOnly="true" showSummary="true"/>

            <ui:insert name="content">Default content</ui:insert>
        </h:panelGroup>


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <h:outputScript library="webjars/bootstrap/4.0.0-alpha/js" name="bootstrap.min.js"/>
    </h:body>
</html>